In [157]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

In [158]:
# 1. Chargement des données
df = pd.read_excel("C:/Users/achao/Desktop/STAGE/Covid_Niger/Files of pj/base_covid_population_vrai/Base_population_Netoyée Pop_VF.xlsx")


## 1 Description Des données

In [159]:
df.T

,0,1,2,3,4,5,6,7,8,9,...,4308,4309,4310,4311,4312,4313,4314,4315,4316,4317
Code,14-01,15-02,15-03,15-05,15-06,16-01,16-02,16-03,16-04,17-01,...,56-02,13-04,41-01,08-12,01-01,20-05,04-02,18-01,21-01,26-02
Longitude,2.09289,2.09289,2.09289,2.09289,2.09289,2.09289,2.09289,2.09289,2.09289,2.09211,...,2.09105,2.07749,2.00771,2.11021,2.11418,2.12634,2.11011,2.11011,2.10523,2.1102
Latitude,13.48281,13.48281,13.48281,13.48281,13.48281,13.48281,13.48281,13.48281,13.48281,13.48278,...,13.48372,13.50636,13.50636,13.5811,13.58341,13.49666,13.47742,13.47742,13.47641,13.581
Quartier_corrige,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,Banga bana,...,Karadje,Lamorde,Lamorde,KOIRA TAGUI,KOIRA TAGUI,GAMKALLEY GOLLEY,Kirkissoye,Kirkissoye,Kirkissoye,KOIRA TAGUI
Population,24700,24700,24700,24700,24700,24700,24700,24700,24700,24700,...,22364,5754,5754,35784,35784,6863,28428,28428,28428,35784
Sexe,Femme,Femme,Homme,Femme,Homme,Femme,Femme,Femme,Homme,Femme,...,Homme,Femme,Femme,Homme,Homme,Homme,Femme,Femme,Homme,Femme
Age,19,60,6,16,2,40,20,17,13,27,...,18,6,75,12,47,48,45,65,14,5
Categorie_age,Adolescent,Personne âgée,Enfant,Adolescent,Enfant,Adulte,Adulte,Adolescent,Adolescent,Adulte,...,Adolescent,Enfant,Personne âgée,Adolescent,Adulte,Adulte,Adulte,Personne âgée,Adolescent,Enfant
Profession,Elève/Etudiant,Sans emploi,Sans emploi,Sans emploi,Sans emploi,Commerçant,Sans emploi,Elève/Etudiant,Elève/Etudiant,Sans emploi,...,Elève/Etudiant,Sans emploi,Sans emploi,Elève/Etudiant,Agriculteur,Sans emploi,Sans emploi,Sans emploi,Elève/Etudiant,Sans emploi
Statut_matrimonial,Marié,Veuf,Célibataire,Marié,Célibataire,Marié,Célibataire,Célibataire,Célibataire,Marié,...,Célibataire,Célibataire,Marié,Célibataire,Marié,Marié,Marié,Marié,Célibataire,Célibataire
Diabte,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
HTA,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Oui,Non,Oui,Non,Oui,Non,Non,Non
Maladie_cardiaque,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Port du masque à domicile,Non,Oui,Oui,Oui,Non,Non,Oui,Non,Non,Non,...,Non,Oui,Non,Non,Non,Non,Oui,Oui,Oui,Non
Port masque exterieur,Oui,Oui,Non,Oui,Non,Oui,Oui,Oui,Non,Non,...,Non,Oui,Non,Non,Oui,Oui,Oui,Oui,Oui,Non
Usage du Gel hydroalcoolique,Non,Rare,Rare,Rare,Rare,Rare,Rare,Rare,Non,Rare,...,Rare,Rare,Non,Non,Non,Non,Non,Non,Non,Non
Usage savon et eau,Rare,Fréquent,Rare,Fréquent,Rare,Rare,Rare,Rare,Non,Rare,...,Non,Fréquent,Non,Fréquent,Fréquent,Rare,Rare,Rare,Rare,Rare
Céphalée,Non,Oui,Non,Oui,Non,Non,Oui,Oui,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Douleurs articulaires,Non,Non,Non,Oui,Non,Oui,Non,Non,Non,Non,...,Non,Non,Non,Non,Oui,Non,Oui,Oui,Non,Non
Fièvre,Non,Oui,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Douleurs musculaires,Non,Non,Non,Oui,Non,Oui,Non,Non,Non,Non,...,Non,Non,Non,Non,Oui,Non,Oui,Oui,Non,Non
Douleurs abdominales,Oui,Oui,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Oui,Non,Non,Non
Toux,Non,Non,Non,Non,Non,Non,Oui,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Rhinorrhée,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Anosmie,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Ageusie,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Frissons,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Nausées,Non,Non,Non,Non,Non,Non,Oui,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Oui,Non,Non,Non
Dyspnée,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Vomissements,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Sueurs,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Eruption cutanée,Non,Non,Non,Oui,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Odynophagie,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Conjonctivite,Non,Non,Non,Non,Non,Oui,Non,Non,Non,Non,...,Non,Oui,Non,Non,Non,Non,Non,Non,Non,Oui
Rhinorragie,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non,...,Non,Non,Non,Non,Non,Non,Non,Non,Non,Non
Serologie,Positif,Positif,Positif,Positif,Négatif,Positif,Positif,Positif,Positif,Positif,...,Négatif,Négatif,Positif,Négatif,Positif,Positif,Négatif,Positif,Négatif,Positif

In [160]:
markdown_table = df.to_markdown(index=False)
print(markdown_table)

| Code   |   Longitude |   Latitude | Quartier_corrige   |   Population | Sexe   |   Age | Categorie_age   | Profession         | Statut_matrimonial   | Diabte   | HTA   | Maladie_cardiaque   | Port du masque à domicile   | Port masque exterieur   | Usage du Gel hydroalcoolique   | Usage savon et eau   | Céphalée   | Douleurs articulaires   | Fièvre   | Douleurs musculaires   | Douleurs abdominales   | Toux   | Rhinorrhée   | Anosmie   | Ageusie   | Frissons   | Nausées   | Dyspnée   | Vomissements   | Sueurs   | Eruption cutanée   | Odynophagie   | Conjonctivite   | Rhinorragie   | Serologie   |
|:-------|------------:|-----------:|:-------------------|-------------:|:-------|------:|:----------------|:-------------------|:---------------------|:---------|:------|:--------------------|:----------------------------|:------------------------|:-------------------------------|:---------------------|:-----------|:------------------------|:---------|:-----------------------|:-----------------------|:-------|:-------------|:----------|:----------|:-----------|:----------|:----------|:---------------|:---------|:-------------------|:--------------|:----------------|:--------------|:------------|
| 14-01  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    19 | Adolescent      | Elève/Etudiant     | Marié                | Non      | Non   | Non                 | Non                         | Oui                     | Non                            | Rare                 | Non        | Non                     | Non      | Non                    | Oui                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 15-02  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    60 | Personne âgée   | Sans emploi        | Veuf                 | Non      | Non   | Non                 | Oui                         | Oui                     | Rare                           | Fréquent             | Oui        | Non                     | Oui      | Non                    | Oui                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 15-03  |     2.09289 |   13.4828  | Banga bana         |        24700 | Homme  |     6 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Oui                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 15-05  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    16 | Adolescent      | Sans emploi        | Marié                | Non      | Non   | Non                 | Oui                         | Oui                     | Rare                           | Fréquent             | Oui        | Oui                     | Non      | Oui                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Oui                | Non           | Non             | Non           | Positif     |
| 15-06  |     2.09289 |   13.4828  | Banga bana         |        24700 | Homme  |     2 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 16-01  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    40 | Adulte          | Commerçant         | Marié                | Non      | Non   | Non                 | Non                         | Oui                     | Rare                           | Rare                 | Non        | Oui                     | Non      | Oui                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Oui             | Non           | Positif     |
| 16-02  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    20 | Adulte          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Oui                         | Oui                     | Rare                           | Rare                 | Oui        | Non                     | Non      | Non                    | Non                    | Oui    | Non          | Non       | Non       | Non        | Oui       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 16-03  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    17 | Adolescent      | Elève/Etudiant     | Célibataire          | Non      | Non   | Non                 | Non                         | Oui                     | Rare                           | Rare                 | Oui        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 16-04  |     2.09289 |   13.4828  | Banga bana         |        24700 | Homme  |    13 | Adolescent      | Elève/Etudiant     | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Non                            | Non                  | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 17-01  |     2.09211 |   13.4828  | Banga bana         |        24700 | Femme  |    27 | Adulte          | Sans emploi        | Marié                | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 17-02  |     2.09211 |   13.4828  | Banga bana         |        24700 | Homme  |     4 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Fréquent                       | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 17-03  |     2.09211 |   13.4828  | Banga bana         |        24700 | Homme  |     1 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Non                            | Non                  | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 18-01  |     2.09211 |   13.4828  | Banga bana         |        24700 | Femme  |    32 | Adulte          | Sans emploi        | Marié                | Non      | Non   | Non                 | Oui                         | Oui                     | Rare                           | Fréquent             | Oui        | Oui                     | Oui      | Oui                    | Oui                    | Non    | Non          | Non       | Oui       | Non        | Oui       | Non       | Oui            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 18-02  |     2.09211 |   13.4828  | Banga bana         |        24700 | Femme  |     1 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Oui      | Non                    | Non                    | Oui    | Oui          | Non       | Non       | Non        | Oui       | Oui       | Oui            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 18-03  |     2.09211 |   13.4828  | Banga bana         |        24700 | Homme  |     6 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Oui        | Non                     | Oui      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Oui            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 18-04  |     2.09211 |   13.4828  | Banga bana         |        24700 | Femme  |    22 | Adulte          | Elève/Etudiant     | Célibataire          | Non      | Non   | Non                 | Non                         | Oui                     | Rare                           | Rare                 | Oui        | Non                     | Oui      | Non                    | Oui                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 19-02  |     2.09294 |   13.4828  | Banga bana         |        24700 | Femme  |    50 | Adulte          | Sans emploi        | Veuf                 | Non      | Non   | Non                 | Non                         | Oui                     | Non                            | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 20-01  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    32 | Adulte          | Sans emploi        | Marié                | Non      | Oui   | Non                 | Non                         | Oui                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 20-02  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    38 | Adulte          | Sans emploi        | Marié                | Non      | Oui   | Oui                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 20-03  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |     4 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Non                  | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 20-04  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |     3 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Oui                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Oui    | Oui          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 21-01  |     2.09289 |   13.4828  | Banga bana         |        24700 | Homme  |    41 | Adulte          | Sans emploi        | Marié                | Non      | Non   | Non                 | Non                         | Oui                     | Non                            | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 21-02  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    28 | Adulte          | Travailleur manuel | Marié                | Non      | Non   | Non                 | Non                         | Oui                     | Rare                           | Non                  | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 21-03  |     2.09289 |   13.4828  | Banga bana         |        24700 | Femme  |    16 | Adolescent      | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Non                  | Non        | Non                     | Oui      | Non                    | Non                    | Oui    | Oui          | Non       | Non       | Non        | Non       | Oui       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 22-01  |     2.09277 |   13.4828  | Banga bana         |        24700 | Femme  |    63 | Personne âgée   | Sans emploi        | Marié                | Non      | Oui   | Non                 | Non                         | Oui                     | Non                            | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |
| 22-03  |     2.09277 |   13.4828  | Banga bana         |        24700 | Femme  |     4 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Non                            | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 22-04  |     2.09277 |   13.4828  | Banga bana         |        24700 | Homme  |     2 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Oui                | Non           | Non             | Non           | Négatif     |
| 22-05  |     2.09277 |   13.4828  | Banga bana         |        24700 | Femme  |    25 | Adulte          | Sans emploi        | Marié                | Non      | Non   | Non                 | Oui                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 22-06  |     2.09277 |   13.4828  | Banga bana         |        24700 | Femme  |     4 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Oui                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 22-07  |     2.09277 |   13.4822  | Banga bana         |        24700 | Homme  |     2 | Enfant          | Sans emploi        | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Négatif     |
| 22-08  |     2.09277 |   13.4828  | Banga bana         |        24700 | Homme  |    15 | Adolescent      | Elève/Etudiant     | Célibataire          | Non      | Non   | Non                 | Non                         | Non                     | Rare                           | Rare                 | Non        | Non                     | Non      | Non                    | Non                    | Non    | Non          | Non       | Non       | Non        | Non       | Non       | Non            | Non      | Non                | Non           | Non             | Non           | Positif     |


---

# Description of the Different Types of Variables

The dataset contains several categories of variables describing the individuals, their health condition, and their behaviors related to disease prevention.

---

## i). Demographic and Geographic Variables

Variables :

`Code, Longitude, Latitude, Quartier_corrige, Population`

**Description**

These variables describe the **geographic location and spatial distribution of individuals** in the study.

* **Code** : Unique identifier assigned to each individual in the dataset.
* **Longitude / Latitude** : Geographic coordinates indicating the precise location of the individual or household.
* **Quartier_corrige** : Name of the neighborhood where the individual lives. This variable is used to analyze the **spatial distribution of cases**.
* **Population** : Estimated population of the neighborhood.

These variables are important for **geographic analysis and identifying spatial clusters of cases**.

---

## 2i). Socio-Demographic Characteristics

Variables :

`Sexe, Age, Categorie_age, Profession, Statut_matrimonial`

**Description**

These variables describe the **social and demographic characteristics of the individuals** included in the study population.

* **Sexe** : Gender of the individual (male or female).
* **Age** : Age of the individual in years.
* **Categorie_age** : Age group classification used to facilitate population analysis.
* **Profession** : Occupation of the individual. This variable can reflect differences in exposure risk.
* **Statut_matrimonial** : Marital status of the individual (single, married, etc.).

These variables help describe the **structure of the study population and identify demographic patterns related to infection risk**.

---

## 3i). Comorbidities

Variables :

`Diabte, HTA, Maladie_cardiaque`

**Description**

These variables represent **pre-existing health conditions** that may influence susceptibility to infection or severity of the disease.

* **Diabte** : Indicates whether the individual has diabetes.
* **HTA** : Indicates whether the individual has hypertension.
* **Maladie_cardiaque** : Indicates the presence of heart disease.

Comorbidities are important because they may **increase vulnerability to infectious diseases and complications**.

---

## 4i). Symptoms

Variables :

Céphalée, Douleurs articulaires, Fièvre, Douleurs musculaires,
Douleurs abdominales, Toux, Rhinorrhée, Anosmie, Ageusie,
Frissons, Nausées, Dyspnée, Vomissements, Sueurs,
Eruption cutanée, Odynophagie, Conjonctivite, Rhinorragie

**Description**

These variables indicate whether individuals reported **clinical symptoms associated with infection**.

Examples include :

* **Fièvre (Fever)**
* **Toux (Cough)**
* **Dyspnée (Difficulty breathing)**
* **Anosmie (Loss of smell)**
* **Ageusie (Loss of taste)**

These variables help identify **symptom patterns associated with serological positivity**.

---

## 5i). Preventive Behaviors

Variables :

Port du masque à domicile, Port masque exterieur,
Usage du Gel hydroalcoolique, Usage savon et eau

**Description**

These variables describe **preventive health behaviors adopted by individuals to reduce the risk of infection**.

* **Port du masque à domicile** : Wearing a mask inside the home.
* **Port masque exterieur** : Wearing a mask in public spaces.
* **Usage du Gel hydroalcoolique** : Use of hand sanitizer.
* **Usage savon et eau** : Handwashing with soap and water.

In [ ]:
print("Nombre d'observations :", df.shape[0])
print("Nombre de variables :", df.shape[1])
n=df.shape[0]
c=df.shape[1]

Nombre d'observations : 4318
Nombre de variables : 36

In [162]:
serology_counts = df['Serologie'].value_counts()
print(serology_counts)

Serologie
Négatif    2848
Positif    1470
Name: count, dtype: int64

In [163]:

sero_counts = df['Serologie'].value_counts()
print("\nRépartition de la sérologie :")
print(sero_counts)

fig_sero = px.pie(
    names=sero_counts.index,
    values=sero_counts.values,
    title="Répartition des résultats sérologiques",
    color_discrete_sequence=['#2ecc71', '#e74c3c'],
    opacity=0.9,
    hole=0.2
)
fig_sero.update_traces(textposition='inside', textinfo='percent+label')
fig_sero.show()

Répartition de la sérologie :
Serologie
Négatif    2848
Positif    1470
Name: count, dtype: int64

## 2 Description des populations

In [164]:
demographic =['Code','Longitude','Latitude','Quartier_corrige','Population']
Characteristics = ['Sexe','Age','Categorie_age','Profession','Statut_matrimonial']
comorbidites = ['Diabte', 'HTA', 'Maladie_cardiaque']
symptomes = ['Céphalée', 'Douleurs articulaires', 'Fièvre', 'Douleurs musculaires', 
             'Douleurs abdominales', 'Toux', 'Rhinorrhée', 'Anosmie', 'Ageusie', 
             'Frissons', 'Nausées', 'Dyspnée', 'Vomissements', 'Sueurs', 
             'Eruption cutanée', 'Odynophagie', 'Conjonctivite', 'Rhinorragie']
comportements = ['Port du masque à domicile', 'Port masque exterieur', 
                 'Usage du Gel hydroalcoolique', 'Usage savon et eau']

features = comorbidites + symptomes + comportements + demographic + Characteristics

In [165]:

sexe_counts = df['Sexe'].value_counts(normalize=True) * 100
sexe_counts = sexe_counts.reset_index()
sexe_counts.columns = ['Sexe', 'Pourcentage']
fig_sexe = px.bar(
    sexe_counts,
    x='Sexe',
    y='Pourcentage',
    text=sexe_counts['Pourcentage'].round(1),
    title='Répartition par sexe (%)',
    color='Sexe',
    color_discrete_sequence=['#3498db', '#e91e63'],
    height=530
)

fig_sexe.update_traces(
    texttemplate='%{text}%',
    textposition='inside'
)

fig_sexe.update_layout(
    template='plotly_white',
    yaxis_title='Pourcentage (%)'
)

fig_sexe.show()

In [166]:

fig_age = px.histogram(df, x='Age', nbins=30, marginal='box',
                       title='Distribution de l\'âge',
                       color_discrete_sequence=["#3dadc6"])
fig_age.add_vline(x=df['Age'].mean(), line_dash="dash", line_color="red",
                  annotation_text=f"Moyenne = {df['Age'].mean():.1f}")
fig_age.add_vline(x=df['Age'].median(), line_dash="dash", line_color="blue",
                  annotation_text=f"Médiane = {df['Age'].median():.1f}")
fig_age.show()

In [167]:

# Ordre souhaité
order_agecat = ['Enfant', 'Adolescent', 'Adulte', 'Personne âgée']

# Compter les effectifs et pourcentages (réindexation pour respecter l'ordre)
counts = df['Categorie_age'].value_counts().reindex(order_agecat, fill_value=0)
percent = df['Categorie_age'].value_counts(normalize=True).reindex(order_agecat, fill_value=0) * 100

# Construire le DataFrame pour Plotly
agecat_counts = counts.reset_index()
agecat_counts.columns = ['Categorie_age', 'Effectif']
agecat_counts['Pourcentage'] = percent.values  # valeurs dans le même ordre

# Créer l'étiquette combinée : "Effectif (X.X%)"
agecat_counts['label'] = (
    agecat_counts['Effectif'].astype(str) 
    + ' (' 
    + agecat_counts['Pourcentage'].round(1).astype(str) 
    + '%)'
)

# Tracer le graphique
fig_agecat = px.bar(
    agecat_counts,
    x='Categorie_age',
    y='Effectif',
    text='label',
    title="Répartition par catégorie d'âge",
    color='Categorie_age',
    color_discrete_sequence=px.colors.qualitative.Pastel
)

# Positionner le texte à l'intérieur des barres
fig_agecat.update_traces(textposition='auto',textangle=0)

# Ajuster la mise en page
fig_agecat.update_layout(
    template='plotly_white',
    yaxis_title='Effectif'
)

# Afficher
fig_agecat.show()

In [168]:
# Calcul des pourcentages
total = len(df)
prof_counts = df['Profession'].value_counts().reset_index()
prof_counts.columns = ['Profession', 'Effectif']
prof_counts['Pourcentage'] = (prof_counts['Effectif'] / total * 100).round(1)
# Créer une étiquette combinée
prof_counts['label'] = prof_counts['Effectif'].astype(str) + ' (' + prof_counts['Pourcentage'].astype(str) + '%)'

fig_prof = px.bar(
    prof_counts,
    x='Effectif',
    y='Profession',
    text='label',
    orientation='h',
    title='Répartition par profession',
    color='Profession',
    color_discrete_sequence=px.colors.qualitative.Set2
)
fig_prof.update_traces(
    textposition='auto',  # ou 'inside' selon préférence
    textangle=0
)
fig_prof.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    template='plotly_white'
)
fig_prof.show()

In [169]:

# Compter les effectifs et calculer les pourcentages
statut_counts = df['Statut_matrimonial'].value_counts().reset_index()
statut_counts.columns = ['Statut', 'Effectif']
statut_counts['Pourcentage'] = (statut_counts['Effectif'] / total * 100).round(1)

# Créer l'étiquette combinée : "Effectif (X.X%)"
statut_counts['label'] = (
    statut_counts['Effectif'].astype(str) 
    + ' (' 
    + statut_counts['Pourcentage'].astype(str) 
    + '%)'
)

# Tracer le graphique vertical
fig_statut = px.bar(
    statut_counts,
    x='Statut',
    y='Effectif',
    text='label',
    title="Répartition par statut matrimonial",
    color='Statut',
    color_discrete_sequence=px.colors.qualitative.Set3
)

# Placer le texte à l'intérieur des barres, horizontalement
fig_statut.update_traces(
    textposition='auto',
    textangle=0
)

# Ajuster la mise en page
fig_statut.update_layout(
    template='plotly_white',
    yaxis_title='Effectif'
)

fig_statut.show()

## 3 - Description geographique

In [170]:


required = ['Latitude', 'Longitude', 'Quartier_corrige', 'Population', 'Serologie']

# =============================================================================
# 2. Carte interactive des individus (échantillon pour lisibilité)
# =============================================================================
# Si trop de points, on peut prendre un échantillon aléatoire
sample_size = min(400, len(df))  # Limiter à 2000 points pour fluidité
df_sample = df.sample(n=sample_size, random_state=42)

fig_map = px.scatter_mapbox(
    df_sample,
    lat='Latitude',
    lon='Longitude',
    color='Serologie',
    color_discrete_map={'Positif': "#f43f2b", 'Négatif': '#2ecc71'},
    zoom=11,
    mapbox_style='carto-positron',# map 
    title="Localisation des individus (échantillon aléatoire)",
    hover_data={'Quartier_corrige': True, 'Population': True}
)
fig_map.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_map.show()
# fig_map.write_html("carte_individus.html")

# =============================================================================
# 3. Agrégation par quartier
# =============================================================================
quartier_stats = df.groupby('Quartier_corrige').agg(
    Total=('Serologie', 'count'),
    Positifs=('Serologie', lambda x: (x == 'Positif').sum()),
    Population=('Population', 'first')  # Population identique pour tout le quartier
).reset_index()
quartier_stats['Taux_positivite'] = (quartier_stats['Positifs'] / quartier_stats['Total'] * 100).round(1)
quartier_stats['Prevalence'] = (quartier_stats['Positifs'] / quartier_stats['Population'] * 100).round(3)

print("\nStatistiques par quartier (5 premiers) :")
print(quartier_stats.head().to_string(index=False))

# =============================================================================
# 4. Graphique : effectifs total et positifs par quartier
# =============================================================================
# Trier par nombre de positifs décroissant pour meilleure lisibilité
quartier_sorted = quartier_stats.sort_values('Positifs', ascending=False)

fig_quartier = make_subplots(rows=1, cols=1)
fig_quartier.add_trace(go.Bar(
    y=quartier_sorted['Quartier_corrige'],
    x=quartier_sorted['Total'],
    name='Total',
    orientation='h',
    marker_color='lightgray',
    hovertemplate='<b>%{y}</b><br>Total: %{x}<extra></extra>'
))
fig_quartier.add_trace(go.Bar(
    y=quartier_sorted['Quartier_corrige'],
    x=quartier_sorted['Positifs'],
    name='Positifs',
    orientation='h',
    marker_color='#e74c3c',
    hovertemplate='<b>%{y}</b><br>Positifs: %{x}<br>Taux: %{customdata}%<extra></extra>',
    customdata=quartier_sorted['Taux_positivite']
))
fig_quartier.update_layout(
    title="Individus et cas positifs par quartier",
    xaxis_title='Effectif',
    yaxis_title='Quartier',
    barmode='overlay',
    height=600
)
fig_quartier.show()
# fig_quartier.write_html("quartier_barres.html")

# =============================================================================
# 5. Relation entre population du quartier et nombre de cas
# =============================================================================
# Nuage de points : population vs. nombre de cas positifs
fig_pop = px.scatter(
    quartier_stats,
    x='Population',
    y='Positifs',
    size='Total',
    color='Taux_positivite',
    hover_name='Quartier_corrige',
    hover_data={'Total': True, 'Taux_positivite': True},
    title="Population du quartier vs. nombre de cas positifs",
    labels={'Population': 'Population du quartier', 'Positifs': 'Nombre de cas positifs'},
    color_continuous_scale='Reds'
)
# Ajouter une ligne de tendance (optionnel)
# Ajout manuel d'une droite de régression simple
from sklearn.linear_model import LinearRegression
X = quartier_stats['Population'].values.reshape(-1, 1)
y = quartier_stats['Positifs'].values
model = LinearRegression().fit(X, y)
x_line = np.linspace(0, quartier_stats['Population'].max(), 100)
y_line = model.predict(x_line.reshape(-1, 1))
fig_pop.add_trace(go.Scatter(
    x=x_line, y=y_line,
    mode='lines',
    name='Régression linéaire',
    line=dict(color='black', dash='dash')
))
fig_pop.show()
# fig_pop.write_html("population_vs_positifs.html")

# =============================================================================
# 7. Carte choroplèthe des quartiers (si nous avons des polygones, mais ici seulement centroïdes)
# =============================================================================
# On peut représenter les quartiers par un point avec une taille proportionnelle au nombre de cas.
# Pour une carte choroplèthe il faudrait les contours géographiques, ce que nous n'avons pas.
# Alternative : utiliser des marqueurs de taille variable sur la carte.
fig_map2 = px.scatter_mapbox(
    quartier_stats,
    lat=df.groupby('Quartier_corrige')['Latitude'].mean().values,
    lon=df.groupby('Quartier_corrige')['Longitude'].mean().values,
    size='Total',
    color='Taux_positivite',
    hover_name='Quartier_corrige',
    hover_data={'Total': True, 'Positifs': True, 'Population': True},
    color_continuous_scale='Reds',
    mapbox_style='carto-positron',
    zoom=11,
    title="Quartiers : taille = nombre total testés, couleur = taux de positivité"
)
fig_map2.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_map2.show()
# fig_map2.write_html("carte_quartiers.html")

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\1394280447.py:10: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

Statistiques par quartier (5 premiers) :
Quartier_corrige  Total  Positifs  Population  Taux_positivite  Prevalence
     AEROPORT II    198        69        7875             34.8       0.876
     Aeroport II    106        26        7875             24.5       0.330
      Banga bana    126        66       24700             52.4       0.267
 Bangou/Tondibia     80        33        1559             41.2       2.117
      Banifandou     15         4       16880             26.7       0.024

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\1394280447.py:112: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

In [171]:
len(df['Quartier_corrige'].value_counts())

30

In [172]:
top15_taux = quartier_stats.sort_values('Taux_positivite', ascending=False).head(15)
fig_taux = px.bar(top15_taux, x='Taux_positivite', y='Quartier_corrige',
                  orientation='h', text='Taux_positivite',
                  title='Taux de positivité par quartier (top 15)',
                  color='Taux_positivite', color_continuous_scale='Reds')
fig_taux.update_traces(texttemplate='%{text:.1f}%', textposition='outside')
fig_taux.update_layout(xaxis_title='Taux (%)', yaxis_title='')
fig_taux.show()

## 4- Destribution du Serologie

In [173]:
def plot_serologie_by_variable(df, variable):
    """
    Crée un graphique à barres horizontales comparant le total d'individus
    et les cas positifs pour chaque modalité d'une variable catégorielle.

    Paramètres :
    - df : DataFrame contenant les données.
    - variable : nom de la colonne catégorielle à analyser.
    - show_total_pct : booléen, si True ajoute le pourcentage du total de chaque
                       modalité par rapport à l'ensemble (par défaut False).
    """
    show_total_pct=True
    # Agrégation des données
    stats = df.groupby(variable).agg(
        Total=('Serologie', 'count'),
        Positifs=('Serologie', lambda x: (x == 'Positif').sum())
    ).reset_index()

    stats['Taux_positivite'] = (stats['Positifs'] / stats['Total'] * 100).round(1)

    if show_total_pct:
        total_global = len(df)
        stats['Pct_total'] = (stats['Total'] / total_global * 100).round(1)

    # Tri par nombre de positifs décroissant (optionnel)
    stats = stats.sort_values('Positifs', ascending=False)

    # Création des labels
    stats['label_total'] = stats['Total'].astype(str)
    if show_total_pct:
        stats['label_total'] += ' (' + stats['Pct_total'].astype(str) + '%)'

    stats['label_positifs'] = (stats['Positifs'].astype(str) +
                               ' (' + stats['Taux_positivite'].astype(str) + '%)')

    # Construction du graphique
    fig = make_subplots(rows=1, cols=1)

    # Barres du total
    fig.add_trace(go.Bar(
        y=stats[variable],
        x=stats['Total'],
        name='Total',
        orientation='h',
        marker_color="#4e98bc",
        text=stats['label_total'],
        textposition='auto',
        hovertemplate='<b>%{y}</b><br>Total: %{x}<extra></extra>'
    ))

    # Barres des positifs
    fig.add_trace(go.Bar(
        y=stats[variable],
        x=stats['Positifs'],
        name='Positifs',
        orientation='h',
        marker_color="#e73c3c",
        text=stats['label_positifs'],
        textposition='auto',
        hovertemplate='<b>%{y}</b><br>Positifs: %{x}<br>Taux: %{customdata}%<extra></extra>',
        customdata=stats['Taux_positivite']
    ))

    # Mise en page
    fig.update_layout(
        title=f'Individus et cas positifs par {variable}',
        xaxis_title='Effectif',
        yaxis_title=variable,
        barmode='stack',
        template='plotly_white',
        height=600
    )

    fig.show()

In [174]:


# --- Graphique 1 : répartition par sexe ---

sexe_counts = df['Sexe'].value_counts().reset_index()
sexe_counts.columns = ['Sexe', 'Effectif']
sexe_counts['Pourcentage'] = (sexe_counts['Effectif'] / total * 100).round(1)
sexe_counts['label'] = sexe_counts['Effectif'].astype(str) + ' (' + sexe_counts['Pourcentage'].astype(str) + '%)'

# --- Graphique 2 : sérologie par sexe ---
sero_sex = df.groupby(['Serologie', 'Sexe']).size().reset_index(name='Effectif')
# Calcul du pourcentage par sexe (total par sexe)
total_par_sexe = df.groupby('Sexe').size().reset_index(name='Total_sexe')
sero_sex = sero_sex.merge(total_par_sexe, on='Sexe')
sero_sex['Pourcentage'] = (sero_sex['Effectif'] / sero_sex['Total_sexe'] * 100).round(1)
sero_sex['label'] = sero_sex['Effectif'].astype(str) + ' (' + sero_sex['Pourcentage'].astype(str) + '%)'

# Création des subplots
fig = make_subplots(
    rows=1, cols=2,
    subplot_titles=("Répartition par sexe", "Résultats sérologiques par sexe")
)

# Graphique 1
fig.add_trace(
    go.Bar(
        x=sexe_counts['Sexe'],
        y=sexe_counts['Effectif'],
        text=sexe_counts['label'],
        textposition='auto',
        marker_color=['#3498db', '#e91e63'],
        name='Sexe',
        showlegend=False
    ),
    row=1, col=1
)

# Graphique 2 : une trace par sérologie
for sero in sero_sex['Serologie'].unique():
    data = sero_sex[sero_sex['Serologie'] == sero]
    color = '#2ecc71' if sero == 'Positif' else '#e74c3c'
    fig.add_trace(
        go.Bar(
            x=data['Sexe'],
            y=data['Effectif'],
            name=sero,
            text=data['label'],
            textposition='auto',
            marker_color=color
        ),
        row=1, col=2
    )

# Mise en page
fig.update_layout(
    title="Analyse du sexe et des résultats sérologiques",
    template="plotly_white",
    height=500,
    barmode='group'  # pour le second graphique (groupé)
)

# Ajuster les axes
fig.update_xaxes(title_text="Sexe", row=1, col=1)
fig.update_yaxes(title_text="Effectif", row=1, col=1)
fig.update_xaxes(title_text="Sexe", row=1, col=2)
fig.update_yaxes(title_text="Effectif", row=1, col=2)

fig.show()

In [175]:
fig_age = px.histogram(df, x='Age', nbins=30, marginal='box',
                       title='Distribution de l\'âge',
                       color_discrete_sequence=["#3dadc6"],facet_col='Serologie')
fig_age.add_vline(x=df['Age'].mean(), line_dash="dash", line_color="red",
                  annotation_text=f"Moyenne = {df['Age'].mean():.1f}")
fig_age.add_vline(x=df['Age'].median(), line_dash="dash", line_color="blue",
                  annotation_text=f"Médiane = {df['Age'].median():.1f}")
fig_age.show()

In [176]:
plot_serologie_by_variable(df,'Categorie_age')

In [177]:
plot_serologie_by_variable(df,'Profession')

In [178]:
plot_serologie_by_variable(df,'Statut_matrimonial')

## 5. Analyse des symptômes

In [179]:
print("\n=== ANALYSE DES SYMPTÔMES ===\n")

n_total = len(df)
# Vérifier que toutes les colonnes existent
symptom_cols = [col for col in symptomes if col in df.columns]
print(f"Nombre de symptômes analysés : {len(symptom_cols)}")

# Fonction pour encoder les symptômes : Oui/Rare/Fréquent -> 1, Non -> 0
def encode_symptom(val):
    if pd.isna(val):
        return np.nan
    if val in ['Oui', 'Rare', 'Fréquent']:
        return 1
    else:
        return 0

# Créer une matrice binaire des symptômes
symptom_matrix = df[symptom_cols].applymap(encode_symptom)

# Fréquence de chaque symptôme (nombre de personnes avec présence)
symptom_freq = symptom_matrix.sum().sort_values(ascending=False).reset_index()
symptom_freq.columns = ['Symptôme', 'Effectif']
symptom_freq['Pourcentage'] = (symptom_freq['Effectif'] / n_total * 100).round(1)

print("\nFréquence des symptômes :")
print(symptom_freq.to_string(index=False))

=== ANALYSE DES SYMPTÔMES ===

Nombre de symptômes analysés : 18

Fréquence des symptômes :
             Symptôme  Effectif  Pourcentage
             Céphalée       822         19.0
Douleurs articulaires       551         12.8
               Fièvre       498         11.5
 Douleurs musculaires       460         10.7
 Douleurs abdominales       388          9.0
           Rhinorrhée       285          6.6
                 Toux       203          4.7
          Odynophagie        88          2.0
     Eruption cutanée        82          1.9
         Vomissements        72          1.7
        Conjonctivite        66          1.5
               Sueurs        63          1.5
              Nausées        62          1.4
             Frissons        31          0.7
              Dyspnée        28          0.6
              Ageusie        13          0.3
              Anosmie        10          0.2
          Rhinorragie         6          0.1

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\3811633197.py:18: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

In [180]:
fig_symp_freq = px.bar(symptom_freq, x='Effectif', y='Symptôme', text='Effectif',
                       orientation='h', title='Fréquence des symptômes',
                       color='Effectif', color_continuous_scale='Viridis')
fig_symp_freq.update_traces(textposition='outside')
fig_symp_freq.update_layout(yaxis={'categoryorder':'total ascending'})
fig_symp_freq.show()

In [181]:

symptom_freq = symptom_freq.sort_values('Effectif', ascending=False)
#symptom_freq = symptom_freq[symptom_freq['Effectif'] > 50]
# Calcul du pourcentage
symptom_freq['Pourcentage'] = (symptom_freq['Effectif'] / symptom_freq['Effectif'].sum() * 100).round(1)

fig_treemap = px.treemap(
    symptom_freq,
    path=['Symptôme'],
    values='Effectif',
    title='Répartition des symptômes',
    color='Effectif',
    color_continuous_scale='Blues'
)

# Améliorer affichage texte
fig_treemap.update_traces(
    textinfo="label+percent entry",
    hovertemplate="<b>%{label}</b><br>Effectif: %{value}<br>%: %{percentEntry:.1%}<extra></extra>"
)

# Améliorer layout
fig_treemap.update_layout(
    template="plotly_white",
    margin=dict(t=50, l=25, r=25, b=25)
)

fig_treemap.show()

## 7- Analyse des comorbidités

In [182]:

comorbidity_cols = [col for col in comorbidites if col in df.columns]

# Encoder de la même manière
def encode_comor(val):
    if pd.isna(val):
        return np.nan
    return 1 if val == 'Oui' else 0

comor_matrix = df[comorbidity_cols].applymap(encode_comor)
comor_freq = comor_matrix.sum().sort_values(ascending=False).reset_index()
comor_freq.columns = ['Comorbidité', 'Effectif']
comor_freq['Pourcentage'] = (comor_freq['Effectif'] / n_total * 100).round(1)

print("\nFréquence des comorbidités :")
print(comor_freq.to_string(index=False))

Fréquence des comorbidités :
      Comorbidité  Effectif  Pourcentage
              HTA       285          6.6
Maladie_cardiaque        76          1.8
           Diabte        75          1.7

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\1500201484.py:9: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

In [183]:
# Calcul du pourcentage par rapport au nombre total d'individus

comor_freq['Pourcentage'] = (comor_freq['Effectif'] / total * 100).round(1)

# Création de l'étiquette combinée : "Effectif (X.X%)"
comor_freq['label'] = (
    comor_freq['Effectif'].astype(str) 
    + ' (' 
    + comor_freq['Pourcentage'].astype(str) 
    + '%)'
)

# Tracer le graphique
fig_comor = px.bar(
    comor_freq,
    x='Comorbidité',
    y='Effectif',
    text='label',
    title='Fréquence des comorbidités',
    color='Comorbidité',
    color_discrete_sequence=px.colors.qualitative.Set1
)

# Placer le texte à l'intérieur des barres, horizontalement
fig_comor.update_traces(
    textposition='auto',
    textangle=0
)

# Ajuster la mise en page
fig_comor.update_layout(
    template='plotly_white',
    yaxis_title='Effectif'
)

fig_comor.show()

In [184]:


# Construction du tableau croisé comorbidité × sérologie (seulement les porteurs)
comor_sero = pd.DataFrame()
for com in comorbidites:
    ct = pd.crosstab(df[com], df['Serologie'])
    if 'Oui' in ct.index:
        row = ct.loc['Oui'].to_frame().T
        row.index = [com]
        comor_sero = pd.concat([comor_sero, row])
    else:
        row = pd.DataFrame({'Négatif': [0], 'Positif': [0]}, index=[com])
        comor_sero = pd.concat([comor_sero, row])

comor_sero = comor_sero.reset_index().rename(columns={'index': 'Comorbidité'})
comor_sero['Total'] = comor_sero['Négatif'] + comor_sero['Positif']
comor_sero['% Positif'] = (comor_sero['Positif'] / comor_sero['Total'] * 100).round(1)

# Passage au format long et ajout du pourcentage pour chaque barre
comor_long = comor_sero.melt(
    id_vars=['Comorbidité', 'Total', '% Positif'],
    value_vars=['Négatif', 'Positif'],
    var_name='Sérologie',
    value_name='Effectif'
)

# Calcul du pourcentage pour chaque modalité (intra‑groupe)
comor_long['Pct'] = comor_long.apply(
    lambda row: row['% Positif'] if row['Sérologie'] == 'Positif' else 100 - row['% Positif'],
    axis=1
).round(1)

# Étiquette combinée : effectif (pourcentage)
comor_long['label'] = (
    comor_long['Effectif'].astype(str) 
    + ' (' 
    + comor_long['Pct'].astype(str) 
    + '%)'
)

# Graphique
fig_comor = px.bar(
    comor_long,
    x='Comorbidité',
    y='Effectif',
    color='Sérologie',
    barmode='group',
    title='Effectifs des comorbidités selon la sérologie',
    text='label',
    color_discrete_sequence=["#eb201c", "#10e86a"],  # rouge négatif, vert positif
    hover_data={'Total': True, '% Positif': True}
)

# Positionnement du texte à l'extérieur des barres
fig_comor.update_traces(textposition='auto')

# Mise en page
fig_comor.update_layout(
    xaxis_title='Comorbidité',
    yaxis_title="Nombre d'individus",
    legend_title='Sérologie',
    uniformtext_minsize=8,
    uniformtext_mode='hide',
    template='plotly_white'
)

fig_comor.show()

In [185]:

preventive_cols = ['Port du masque à domicile', 'Port masque exterieur',
                   'Usage du Gel hydroalcoolique', 'Usage savon et eau']
preventive_cols = [col for col in preventive_cols if col in df.columns]



preventive_dfs = []
for col in preventive_cols:
    counts = df[col].value_counts().reset_index()
    counts.columns = ['Réponse', 'Effectif']
    counts['Comportement'] = col
    counts['Pourcentage'] = (counts['Effectif'] / total * 100).round(1)
    counts['label'] = counts['Effectif'].astype(str) + ' (' + counts['Pourcentage'].astype(str) + '%)'
    preventive_dfs.append(counts)

preventive_df = pd.concat(preventive_dfs, ignore_index=True)

print("\nDistribution des comportements préventifs :")
print(preventive_df.to_string(index=False))

fig_prev = px.bar(
    preventive_df,
    x='Comportement',
    y='Effectif',
    color='Réponse',
    barmode='group',
    title='Comportements préventifs',
    text='label',
    color_discrete_sequence=px.colors.qualitative.Set2
)

fig_prev.update_traces(textposition='outside')
fig_prev.update_layout(uniformtext_minsize=8)
fig_prev.show()

Distribution des comportements préventifs :
 Réponse  Effectif                 Comportement  Pourcentage        label
     Non      4094    Port du masque à domicile         94.8 4094 (94.8%)
     Oui       224    Port du masque à domicile          5.2   224 (5.2%)
     Non      2567        Port masque exterieur         59.4 2567 (59.4%)
     Oui      1751        Port masque exterieur         40.6 1751 (40.6%)
     Non      2045 Usage du Gel hydroalcoolique         47.4 2045 (47.4%)
    Rare      2012 Usage du Gel hydroalcoolique         46.6 2012 (46.6%)
Fréquent       261 Usage du Gel hydroalcoolique          6.0   261 (6.0%)
    Rare      1947           Usage savon et eau         45.1 1947 (45.1%)
Fréquent      1832           Usage savon et eau         42.4 1832 (42.4%)
     Non       539           Usage savon et eau         12.5  539 (12.5%)

## 8- cooccurrence des symptômes

In [186]:
# Graphique des symptômes les plus fréquents
# À exécuter dans une cellule de votre notebook après avoir calculé symptom_freq

fig_freq = px.bar(
    symptom_freq,
    x='Effectif',
    y='Symptôme',
    orientation='h',
    text='Effectif',
    title='Symptômes les plus fréquents',
    labels={'Effectif': "Nombre d'individus", 'Symptôme': ''},
    color='Effectif',
    color_continuous_scale='Viridis'
)

# Ajout du pourcentage dans le survol
fig_freq.update_traces(
    textposition='outside',
    hovertemplate='<b>%{y}</b><br>Effectif: %{x}<br>Pourcentage: %{customdata:.1f}%<extra></extra>',
    customdata=symptom_freq['Pourcentage']
)

# Amélioration de la mise en page
fig_freq.update_layout(
    yaxis={'categoryorder': 'total ascending'},
    height=600,
    margin=dict(l=200)  # espace pour les noms des symptômes
)

fig_freq.show()

In [187]:

print("\n=== CORRÉLATION ENTRE SYMPTÔMES ===\n")

# Matrice de corrélation de Pearson (après encodage binaire)
corr_matrix = symptom_matrix.corr()

# Créer un heatmap interactif
fig_corr = px.imshow(corr_matrix,
                     text_auto=True,
                     aspect="auto",
                     color_continuous_scale='RdBu_r',
                     zmin=-1, zmax=1,
                     title="Matrice de corrélation des symptômes")
fig_corr.update_layout(height=800, width=1000)
fig_corr.show()

=== CORRÉLATION ENTRE SYMPTÔMES ===

In [188]:

# 1. Calcul des co‑occurrences
cooc_dict = {}
for i, symp1 in enumerate(symptomes):
    for symp2 in symptomes[i+1:]:
        count = ((symptom_matrix[symp1] == 1) & (symptom_matrix[symp2] == 1)).sum()
        if count > 0:
            cooc_dict[(symp1, symp2)] = count

# 2. Création de la matrice de co‑occurrence (remplie de zéros)
cooc_matrix = pd.DataFrame(0, index=symptomes, columns=symptomes)

# 3. Remplissage de la matrice avec les valeurs du dictionnaire
for (s1, s2), cnt in cooc_dict.items():
    cooc_matrix.loc[s1, s2] = cnt
    cooc_matrix.loc[s2, s1] = cnt   # symétrique

# 4. Heatmap interactive
fig_cooc = px.imshow(
    cooc_matrix,
    text_auto=True,
    aspect="auto",
    color_continuous_scale='Blues',
    title="Co‑occurrence des symptômes (nombre d'individus)"
)
fig_cooc.update_layout(height=800, width=1000)
fig_cooc.show()

In [189]:
import copy
corr_masked = copy.copy(corr_matrix)
corr_masked[abs(corr_masked) < 0.3] = None

fig_corr_masked = px.imshow(corr_masked,
                            text_auto=True,
                            aspect="auto",
                            color_continuous_scale='RdBu_r',
                            zmin=-1, zmax=1,
                            title="Corrélations significatives (|r| ≥ 0.3)")
fig_corr_masked.update_layout(height=800, width=1000)
fig_corr_masked.show()

In [190]:
import itertools

# Liste des symptômes
symptom_list = symptom_matrix.columns

# Dictionnaire pour stocker les co-occurrences
cooc = {}
for i, symp1 in enumerate(symptom_list):
    for symp2 in symptom_list[i+1:]:
        # Nombre d'individus ayant les deux symptômes
        count = ((symptom_matrix[symp1] == 1) & (symptom_matrix[symp2] == 1)).sum()
        if count > 0:
            cooc[(symp1, symp2)] = count

# Trier par fréquence décroissante
sorted_pairs = sorted(cooc.items(), key=lambda x: x[1], reverse=True)

# Afficher les 10 premières paires
print("Top 10 des paires de symptômes les plus fréquentes :")
for (s1, s2), cnt in sorted_pairs[:10]:
    print(f"{s1} + {s2} : {cnt} personnes")

Top 10 des paires de symptômes les plus fréquentes :
Douleurs articulaires + Douleurs musculaires : 359 personnes
Céphalée + Fièvre : 239 personnes
Céphalée + Douleurs articulaires : 204 personnes
Douleurs articulaires + Fièvre : 142 personnes
Céphalée + Douleurs musculaires : 141 personnes
Céphalée + Douleurs abdominales : 135 personnes
Toux + Rhinorrhée : 115 personnes
Fièvre + Douleurs abdominales : 93 personnes
Fièvre + Douleurs musculaires : 89 personnes
Douleurs articulaires + Douleurs abdominales : 82 personnes

In [191]:
symptom_list = symptom_matrix.columns

# Dictionnaire pour stocker les co-occurrences
cooc = {}
for i, symp1 in enumerate(symptom_list):
    for symp2 in symptom_list[i+1:]:
        # Nombre d'individus ayant les deux symptômes
        count = ((symptom_matrix[symp1] == 1) & (symptom_matrix[symp2] == 1)).sum()
        if count > 0:
            cooc[(symp1, symp2)] = count

# Trier par fréquence décroissante et extraire le top 10
sorted_pairs = sorted(cooc.items(), key=lambda x: x[1], reverse=True)
top_10_pairs = sorted_pairs[:10]

# Préparer les données pour Plotly
noms_paires = [f"{s1} + {s2}" for (s1, s2), cnt in top_10_pairs]
comptes = [cnt for (s1, s2), cnt in top_10_pairs]

df_cooc = pd.DataFrame({
    'Paires de symptômes': noms_paires,
    'Effectif': comptes
})

# Création du graphique
fig_cooc = px.bar(
    df_cooc, 
    x='Effectif', 
    y='Paires de symptômes', 
    orientation='h',
    text='Effectif',
    title='Top 10 des paires de symptômes les plus fréquentes',
    color='Effectif',
    color_continuous_scale='Viridis'
)

# Amélioration de l'affichage (ordre croissant pour avoir le plus grand en haut)
fig_cooc.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_cooc.update_traces(textposition='auto')

# Afficher le graphique
fig_cooc.show()

In [192]:
print("\n=== Symptômes vs Sérologie ===")

# Liste des colonnes de symptômes (doivent exister dans le DataFrame)
symptom_cols = [
    'Céphalée', 'Douleurs articulaires', 'Fièvre', 'Douleurs musculaires',
    'Douleurs abdominales', 'Toux', 'Rhinorrhée', 'Anosmie', 'Ageusie',
    'Frissons', 'Nausées', 'Dyspnée', 'Vomissements', 'Sueurs',
    'Eruption cutanée', 'Odynophagie', 'Conjonctivite', 'Rhinorragie'
]
# Garder uniquement celles qui existent dans le DataFrame
symptom_cols = [col for col in symptom_cols if col in df.columns]

# Encodage binaire des symptômes (0 = Non, 1 = Oui/Rare/Fréquent)
def encode_binary(val):
    if pd.isna(val):
        return np.nan
    return 1 if val in ['Oui', 'Rare', 'Fréquent'] else 0

symptom_bin = df[symptom_cols].applymap(encode_binary)
symptom_bin['Serologie'] = df['Serologie']

# Calcul pour chaque symptôme : effectifs et pourcentages de positifs
results_symp = []
for symp in symptom_cols:
    # Tableau croisé entre présence du symptôme (0/1) et sérologie
    ct = pd.crosstab(symptom_bin[symp], symptom_bin['Serologie'])
    # Extraction des valeurs (avec gestion des cas où une modalité serait absente)
    pos_avec = ct.loc[1, 'Positif'] if 1 in ct.index and 'Positif' in ct.columns else 0
    neg_avec = ct.loc[1, 'Négatif'] if 1 in ct.index and 'Négatif' in ct.columns else 0
    pos_sans = ct.loc[0, 'Positif'] if 0 in ct.index and 'Positif' in ct.columns else 0
    neg_sans = ct.loc[0, 'Négatif'] if 0 in ct.index and 'Négatif' in ct.columns else 0

    total_avec = pos_avec + neg_avec
    total_sans = pos_sans + neg_sans
    pct_pos_avec = (pos_avec / total_avec * 100) if total_avec else 0
    pct_pos_sans = (pos_sans / total_sans * 100) if total_sans else 0

    results_symp.append({
        'Symptôme': symp,
        'Avec_symptome': total_avec,
        'Positifs_avec': pos_avec,
        'Pourcentage_pos_avec': pct_pos_avec,
        'Sans_symptome': total_sans,
        'Positifs_sans': pos_sans,
        'Pourcentage_pos_sans': pct_pos_sans
    })

df_symp_sero = pd.DataFrame(results_symp)
df_symp_sero = df_symp_sero.sort_values('Pourcentage_pos_avec', ascending=False)
df_symp_sero

=== Symptômes vs Sérologie ===

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\3201598227.py:19: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

,Symptôme,Avec_symptome,Positifs_avec,Pourcentage_pos_avec,Sans_symptome,Positifs_sans,Pourcentage_pos_sans
10,Nausées,62,34,54.838710,4256,1436,33.740602
17,Rhinorragie,6,3,50.000000,4312,1467,34.021336
13,Sueurs,63,31,49.206349,4255,1439,33.819036
16,Conjonctivite,66,32,48.484848,4252,1438,33.819379
8,Ageusie,13,6,46.153846,4305,1464,34.006969
12,Vomissements,72,31,43.055556,4246,1439,33.890721
3,Douleurs musculaires,460,198,43.043478,3858,1272,32.970451
7,Anosmie,10,4,40.000000,4308,1466,34.029712
1,Douleurs articulaires,551,214,38.838475,3767,1256,33.342182
5,Toux,203,75,36.945813,4115,1395,33.900365
4,Douleurs abdominales,388,138,35.567010,3930,1332,33.893130
15,Odynophagie,88,30,34.090909,4230,1440,34.042553
0,Céphalée,822,275,33.454988,3496,1195,34.181922
14,Eruption cutanée,82,27,32.926829,4236,1443,34.065156
6,Rhinorrhée,285,85,29.824561,4033,1385,34.341681
2,Fièvre,498,148,29.718876,3820,1322,34.607330
9,Frissons,31,9,29.032258,4287,1461,34.079776
11,Dyspnée,28,8,28.571429,4290,1462,34.079254

In [193]:
print("\n=== Comorbidités vs Sérologie ===")

comorbidity_cols = ['Diabte', 'HTA', 'Maladie_cardiaque']
comorbidity_cols = [col for col in comorbidity_cols if col in df.columns]

# Encodage binaire : 1 si 'Oui', 0 sinon
def encode_comor(val):
    if pd.isna(val):
        return np.nan
    return 1 if val == 'Oui' else 0

comor_bin = df[comorbidity_cols].applymap(encode_comor)
comor_bin['Serologie'] = df['Serologie']

results_comor = []
for com in comorbidity_cols:
    ct = pd.crosstab(comor_bin[com], comor_bin['Serologie'])
    # Même extraction que pour les symptômes
    pos_avec = ct.loc[1, 'Positif'] if 1 in ct.index and 'Positif' in ct.columns else 0
    neg_avec = ct.loc[1, 'Négatif'] if 1 in ct.index and 'Négatif' in ct.columns else 0
    pos_sans = ct.loc[0, 'Positif'] if 0 in ct.index and 'Positif' in ct.columns else 0
    neg_sans = ct.loc[0, 'Négatif'] if 0 in ct.index and 'Négatif' in ct.columns else 0

    total_avec = pos_avec + neg_avec
    total_sans = pos_sans + neg_sans
    pct_pos_avec = (pos_avec / total_avec * 100) if total_avec else 0
    pct_pos_sans = (pos_sans / total_sans * 100) if total_sans else 0

    results_comor.append({
        'Comorbidité': com,
        'Avec': total_avec,
        'Positifs_avec': pos_avec,
        '%positifs_avec': pct_pos_avec,
        'Sans': total_sans,
        'Positifs_sans': pos_sans,
        '%positifs_sans': pct_pos_sans
    })

=== Comorbidités vs Sérologie ===

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\1932528219.py:12: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

In [194]:

df_comor_sero = pd.DataFrame(results_comor)
print("\nComorbidités : proportion de positifs")
print(df_comor_sero.to_string(index=False))

Comorbidités : proportion de positifs
      Comorbidité  Avec  Positifs_avec  %positifs_avec  Sans  Positifs_sans  %positifs_sans
           Diabte    75             36       48.000000  4243           1434       33.796842
              HTA   285            134       47.017544  4033           1336       33.126705
Maladie_cardiaque    76             40       52.631579  4242           1430       33.710514

In [195]:
import pandas as pd
import plotly.express as px

print("\n=== Comportements préventifs vs Sérologie ===")

preventive_cols = [
    'Port du masque à domicile',
    'Port masque exterieur',
    'Usage du Gel hydroalcoolique',
    'Usage savon et eau'
]

# Garder seulement les colonnes existantes
preventive_cols = [col for col in preventive_cols if col in df.columns]

for col in preventive_cols:
    print(f"\n--- {col} ---")

    # ===============================
    # 1. Tableau croisé (effectifs)
    # ===============================
    ct = pd.crosstab(df[col], df['Serologie'])

    # ===============================
    # 2. Pourcentages PAR LIGNE (IMPORTANT)
    # ===============================
    ct_perc = ct.div(ct.sum(axis=1), axis=0) * 100

    print("Effectifs :")
    print(ct)

    print("\nPourcentages ligne (conditionnels) :")
    print(ct_perc.round(1))

    # ===============================
    # 3. Format long
    # ===============================
    ct_long = ct.reset_index().melt(
        id_vars=col,
        var_name='Sérologie',
        value_name='Effectif'
    )

    # Ajouter les pourcentages correspondants
    ct_long['Pourcentage'] = ct_long.apply(
        lambda row: ct_perc.loc[row[col], row['Sérologie']], axis=1
    )

    # ===============================
    # 4. Label = Effectif + %
    # ===============================
    ct_long['label'] = (
        ct_long['Effectif'].astype(str) +
        "<br>" +
        ct_long['Pourcentage'].round(1).astype(str) + "%"
    )

    # ===============================
    # 5. Graphique
    # ===============================
    fig = px.bar(
        ct_long,
        x=col,
        y='Effectif',
        color='Sérologie',
        barmode='group',
        title=f"Comportement : {col}",
        color_discrete_map={
            'Négatif': '#e74c3c',
            'Positif': '#2ecc71'
        },
        text='label'
    )

    fig.update_traces(
        textposition='auto'
    )

    fig.update_layout(
        template='plotly_white',
        uniformtext_minsize=8,
        uniformtext_mode='hide',
        yaxis_title="Nombre d'individus",
        xaxis_title=""
    )

    fig.show()

=== Comportements préventifs vs Sérologie ===

--- Port du masque à domicile ---
Effectifs :
Serologie                  Négatif  Positif
Port du masque à domicile
Non                           2703     1391
Oui                            145       79

Pourcentages ligne (conditionnels) :
Serologie                  Négatif  Positif
Port du masque à domicile
Non                           66.0     34.0
Oui                           64.7     35.3

--- Port masque exterieur ---
Effectifs :
Serologie              Négatif  Positif
Port masque exterieur
Non                       1706      861
Oui                       1142      609

Pourcentages ligne (conditionnels) :
Serologie              Négatif  Positif
Port masque exterieur
Non                       66.5     33.5
Oui                       65.2     34.8

--- Usage du Gel hydroalcoolique ---
Effectifs :
Serologie                     Négatif  Positif
Usage du Gel hydroalcoolique
Fréquent                          179       82
Non                              1374      671
Rare                             1295      717

Pourcentages ligne (conditionnels) :
Serologie                     Négatif  Positif
Usage du Gel hydroalcoolique
Fréquent                         68.6     31.4
Non                              67.2     32.8
Rare                             64.4     35.6

--- Usage savon et eau ---
Effectifs :
Serologie           Négatif  Positif
Usage savon et eau
Fréquent               1244      588
Non                     384      155
Rare                   1220      727

Pourcentages ligne (conditionnels) :
Serologie           Négatif  Positif
Usage savon et eau
Fréquent               67.9     32.1
Non                    71.2     28.8
Rare                   62.7     37.3

In [196]:
print("\n=== Comportements préventifs vs Sérologie ===")

preventive_cols = [
    'Port du masque à domicile',
    'Port masque exterieur',
    'Usage du Gel hydroalcoolique',
    'Usage savon et eau'
]
preventive_cols = [col for col in preventive_cols if col in df.columns]

for col in preventive_cols:
    print(f"\n--- {col} ---")

    # Tableau croisé entre la modalité du comportement et la sérologie
    ct = pd.crosstab(df[col], df['Serologie'])
    # Pourcentages en ligne (par modalité de comportement)
    ct_perc = ct.div(ct.sum(axis=1), axis=0) * 100

    print("Effectifs :")
    print(ct)
    print("\nPourcentages ligne :")
    print(ct_perc.round(1))

    # Préparer les données pour le graphique
    ct_long = ct.reset_index().melt(id_vars=col, var_name='Sérologie', value_name='Effectif')
    # Ajouter une colonne pour le pourcentage
    ct_long['Pourcentage'] = 0.0
    for modalite in ct.index:
        for sero in ['Négatif', 'Positif']:
            mask = (ct_long[col] == modalite) & (ct_long['Sérologie'] == sero)
            if mask.any():
                ct_long.loc[mask, 'Pourcentage'] = ct_perc.loc[modalite, sero]

    # Création du graphique
    fig = px.bar(
        ct_long,
        x=col,
        y='Effectif',
        color='Sérologie',
        barmode='group',
        title=f'Effectifs pour {col}',
        color_discrete_sequence=['#e74c3c', '#2ecc71'],
        text='Effectif',
        hover_data={'Pourcentage': True}
    )

    # Mise à jour des étiquettes pour inclure le pourcentage
    fig.update_traces(
        texttemplate='%{text} (%{customdata:.1f}%)',
        textposition='auto',
        customdata=ct_long['Pourcentage'].values
    )

    fig.update_layout(
        uniformtext_minsize=8,
        uniformtext_mode='hide'
    )
    fig.show()
    #Sauvegarde (décommenter si nécessaire)
    #fig.write_html(f"prev_{col.replace(' ','_')}.html")

=== Comportements préventifs vs Sérologie ===

--- Port du masque à domicile ---
Effectifs :
Serologie                  Négatif  Positif
Port du masque à domicile
Non                           2703     1391
Oui                            145       79

Pourcentages ligne :
Serologie                  Négatif  Positif
Port du masque à domicile
Non                           66.0     34.0
Oui                           64.7     35.3

--- Port masque exterieur ---
Effectifs :
Serologie              Négatif  Positif
Port masque exterieur
Non                       1706      861
Oui                       1142      609

Pourcentages ligne :
Serologie              Négatif  Positif
Port masque exterieur
Non                       66.5     33.5
Oui                       65.2     34.8

--- Usage du Gel hydroalcoolique ---
Effectifs :
Serologie                     Négatif  Positif
Usage du Gel hydroalcoolique
Fréquent                          179       82
Non                              1374      671
Rare                             1295      717

Pourcentages ligne :
Serologie                     Négatif  Positif
Usage du Gel hydroalcoolique
Fréquent                         68.6     31.4
Non                              67.2     32.8
Rare                             64.4     35.6

--- Usage savon et eau ---
Effectifs :
Serologie           Négatif  Positif
Usage savon et eau
Fréquent               1244      588
Non                     384      155
Rare                   1220      727

Pourcentages ligne :
Serologie           Négatif  Positif
Usage savon et eau
Fréquent               67.9     32.1
Non                    71.2     28.8
Rare                   62.7     37.3

## 10- analyse des cas positifs :

In [ ]:
# Garder seulement les lignes avec sérologie positive
df_pos = df[df['Serologie'] == 'Positif'].copy()
n_pos = len(df_pos)
print(f"Nombre de cas positifs : {n_pos}")
print(f"Soit {n_pos/len(df)*100:.1f}% de l'échantillon total")

# =============================================================================
# 2. Définition des catégories de variables
# =============================================================================
demographic_vars = ['Sexe', 'Age', 'Categorie_age', 'Profession', 'Statut_matrimonial']
comorbid_vars = ['Diabte', 'HTA', 'Maladie_cardiaque']
symptom_vars = [
    'Céphalée', 'Douleurs articulaires', 'Fièvre', 'Douleurs musculaires',
    'Douleurs abdominales', 'Toux', 'Rhinorrhée', 'Anosmie', 'Ageusie',
    'Frissons', 'Nausées', 'Dyspnée', 'Vomissements', 'Sueurs',
    'Eruption cutanée', 'Odynophagie', 'Conjonctivite', 'Rhinorragie'
]
preventive_vars = [
    'Port du masque à domicile', 'Port masque exterieur',
    'Usage du Gel hydroalcoolique', 'Usage savon et eau'
]
geo_vars = ['Quartier_corrige', 'Population']

# Ne garder que les colonnes existantes
symptom_vars = [col for col in symptom_vars if col in df.columns]
comorbid_vars = [col for col in comorbid_vars if col in df.columns]
preventive_vars = [col for col in preventive_vars if col in df.columns]

# Fonction d'encodage binaire pour les symptômes/comorbidités
def encode_binary(val):
    return 1 if val in ['Oui', 'Rare', 'Fréquent'] else 0

# =============================================================================
# 3. Profil démographique des positifs
# =============================================================================
print("\n" + "="*60)
print("PROFIL DÉMOGRAPHIQUE DES CAS POSITIFS")
print("="*60)

# Sexe
sexe_counts = df_pos['Sexe'].value_counts()
sexe_percent = df_pos['Sexe'].value_counts(normalize=True) * 100
print("\nSexe :")
print(sexe_counts)
print("Pourcentage :")
print(sexe_percent.round(1))

fig_sexe = px.pie(
    names=sexe_counts.index, values=sexe_counts.values,
    title=f"Répartition par sexe parmi les positifs (n={n_pos})",
    color_discrete_sequence=['#3498db', '#e91e63'],
    hole=0.3
)
fig_sexe.update_traces(textposition='inside', textinfo='percent+label')
fig_sexe.show()

# Âge
print(f"\nÂge : moyenne = {df_pos['Age'].mean():.1f}, médiane = {df_pos['Age'].median():.1f}")
fig_age = px.histogram(
    df_pos, x='Age', nbins=30, marginal='box',
    title=f"Distribution de l'âge des positifs (n={n_pos})",
    color_discrete_sequence=['#e74c3c']
)
fig_age.add_vline(x=df_pos['Age'].mean(), line_dash="dash", line_color="black")
fig_age.show()

# Catégorie d'âge
order_age = ['Enfant', 'Adolescent', 'Adulte', 'Personne âgée']
agecat_counts = df_pos['Categorie_age'].value_counts().reindex(order_age)
print("\nCatégorie d'âge :")
print(agecat_counts)

fig_agecat = px.bar(
    x=agecat_counts.index, y=agecat_counts.values,
    title=f"Répartition par catégorie d'âge (positifs)",
    labels={'x': '', 'y': 'Effectif'},
    color=agecat_counts.index,
    color_discrete_sequence=px.colors.qualitative.Pastel,
    text=agecat_counts.values
)
fig_agecat.update_traces(textposition='auto')
fig_agecat.show()

# Profession
prof_counts = df_pos['Profession'].value_counts()
print("\nProfession :")
print(prof_counts)

fig_prof = px.bar(
    x=prof_counts.values, y=prof_counts.index, orientation='h',
    title=f"Répartition par profession (positifs)",
    labels={'x': 'Effectif', 'y': ''},
    color=prof_counts.index,
    color_discrete_sequence=px.colors.qualitative.Set2,
    text=prof_counts.values
)
fig_prof.update_traces(textposition='auto')
fig_prof.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_prof.show()

# Statut matrimonial
statut_counts = df_pos['Statut_matrimonial'].value_counts()
print("\nStatut matrimonial :")
print(statut_counts)

fig_statut = px.bar(
    x=statut_counts.index, y=statut_counts.values,
    title=f"Répartition par statut matrimonial (positifs)",
    labels={'x': '', 'y': 'Effectif'},
    color=statut_counts.index,
    color_discrete_sequence=px.colors.qualitative.Set3,
    text=statut_counts.values
)
fig_statut.update_traces(textposition='outside')
fig_statut.show()

# =============================================================================
# 4. Comorbidités chez les positifs
# =============================================================================
print("\n" + "="*60)
print("COMORBIDITÉS CHEZ LES POSITIFS")
print("="*60)

# Encodage binaire des comorbidités
comor_matrix = df_pos[comorbid_vars].applymap(encode_binary)
comor_freq = comor_matrix.sum().sort_values(ascending=False)
comor_percent = (comor_freq / n_pos * 100).round(1)

comor_df = pd.DataFrame({
    'Comorbidité': comor_freq.index,
    'Effectif': comor_freq.values,
    'Pourcentage': comor_percent.values
})
print("\nPrévalence des comorbidités parmi les positifs :")
print(comor_df.to_string(index=False))

fig_comor = px.bar(
    comor_df,
    x='Comorbidité',
    y='Effectif',
    text='Effectif',
    title=f"Comorbidités chez les positifs (n={n_pos})",
    color='Comorbidité',
    color_discrete_sequence=px.colors.qualitative.Set1,
    hover_data={'Pourcentage': True}
)
fig_comor.update_traces(
    texttemplate='%{text} (%{customdata:.1f}%)',
    textposition='auto',
    customdata=comor_df['Pourcentage'].values
)
fig_comor.show()

# =============================================================================
# 5. Symptômes chez les positifs
# =============================================================================
print("\n" + "="*60)
print("SYMPTÔMES CHEZ LES POSITIFS")
print("="*60)

symptom_matrix = df_pos[symptom_vars].applymap(encode_binary)
symptom_freq = symptom_matrix.sum().sort_values(ascending=False)
symptom_percent = (symptom_freq / n_pos * 100).round(1)

symptom_df = pd.DataFrame({
    'Symptôme': symptom_freq.index,
    'Effectif': symptom_freq.values,
    'Pourcentage': symptom_percent.values
})
print("\nFréquence des symptômes parmi les positifs :")
print(symptom_df.to_string(index=False))

fig_symp = px.bar(
    symptom_df,
    x='Effectif',
    y='Symptôme',
    orientation='h',
    text='Effectif',
    title=f"Symptômes les plus fréquents chez les positifs (n={n_pos})",
    color='Effectif',
    color_continuous_scale='Reds',
    hover_data={'Pourcentage': True}
)
fig_symp.update_traces(
    texttemplate='%{text} (%{customdata:.1f}%)',
    textposition='outside',
    customdata=symptom_df['Pourcentage'].values
)
fig_symp.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_symp.show()

# Nombre de symptômes par individu positif
symptom_count = symptom_matrix.sum(axis=1)
print(f"\nNombre de symptômes par individu positif : moyenne = {symptom_count.mean():.1f}, médiane = {symptom_count.median():.0f}")
fig_count = px.histogram(
    x=symptom_count, nbins=15,
    title="Distribution du nombre de symptômes chez les positifs",
    labels={'x': 'Nombre de symptômes', 'y': 'Effectif'},
    color_discrete_sequence=['#e74c3c']
)
fig_count.add_vline(x=symptom_count.mean(), line_dash="dash", line_color="black")
fig_count.show()

# =============================================================================
# 6. Comportements préventifs chez les positifs
# =============================================================================
print("\n" + "="*60)
print("COMPORTEMENTS PRÉVENTIFS CHEZ LES POSITIFS")
print("="*60)

preventive_list = []
for col in preventive_vars:
    tmp = df_pos[col].value_counts().reset_index()
    tmp.columns = ['Réponse', 'Effectif']
    tmp['Comportement'] = col
    tmp['Pourcentage'] = (tmp['Effectif'] / n_pos * 100).round(1)
    preventive_list.append(tmp)
preventive_df = pd.concat(preventive_list, ignore_index=True)

print("\nDistribution des comportements préventifs parmi les positifs :")
print(preventive_df.to_string(index=False))

fig_prev = px.bar(
    preventive_df,
    x='Comportement',
    y='Effectif',
    color='Réponse',
    barmode='group',
    title=f"Comportements préventifs chez les positifs (n={n_pos})",
    text='Effectif',
    color_discrete_sequence=px.colors.qualitative.Set2,
    hover_data={'Pourcentage': True}
)

fig_prev.show()

# =============================================================================
# 7. Distribution géographique des positifs
# =============================================================================
print("\n" + "="*60)
print("DISTRIBUTION GÉOGRAPHIQUE DES POSITIFS")
print("="*60)

# Agrégation par quartier
quartier_stats = df.groupby('Quartier_corrige').agg(
    Total=('Serologie', 'count'),
    Positifs=('Serologie', lambda x: (x == 'Positif').sum())
).reset_index()
quartier_stats['Taux_positivite'] = (quartier_stats['Positifs'] / quartier_stats['Total'] * 100).round(1)
quartier_stats = quartier_stats.sort_values('Positifs', ascending=False)

# Top 10 quartiers avec le plus de positifs
top10_pos = quartier_stats.head(10)
print("\nTop 10 des quartiers avec le plus de cas positifs :")
print(top10_pos[['Quartier_corrige', 'Positifs', 'Total', 'Taux_positivite']].to_string(index=False))

fig_geo = px.bar(
    top10_pos,
    x='Positifs',
    y='Quartier_corrige',
    orientation='h',
    text='Positifs',
    title="Top 10 des quartiers avec le plus de cas positifs",
    labels={'Positifs': "Nombre de cas positifs", 'Quartier_corrige': ''},
    color='Taux_positivite',
    color_continuous_scale='Reds',
    hover_data={'Total': True, 'Taux_positivite': True}
)
fig_geo.update_traces(textposition='auto')
fig_geo.update_layout(yaxis={'categoryorder': 'total ascending'})
fig_geo.show()

# Carte des cas positifs (échantillon)
# On prend un échantillon pour ne pas surcharger
sample_pos = df_pos.sample(min(1000, len(df_pos)), random_state=42)
fig_map = px.scatter_mapbox(
    sample_pos,
    lat='Latitude',
    lon='Longitude',
    color_discrete_sequence=['#e74c3c'],
    zoom=11,
    mapbox_style='carto-positron',
    title=f"Localisation des cas positifs (échantillon de {len(sample_pos)})",
    hover_data={'Quartier_corrige': True, 'Age': True, 'Sexe': True}
)
fig_map.update_layout(margin=dict(l=0, r=0, t=40, b=0))
fig_map.show()

# =============================================================================
# 8. Synthèse : profil type du cas positif
# =============================================================================
print("\n" + "="*60)
print("SYNTHÈSE : PROFIL TYPE DU CAS POSITIF")
print("="*60)

print(f"\n- Âge moyen : {df_pos['Age'].mean():.1f} ans")
print(f"- Sexe : {sexe_percent['Femme']:.1f}% de femmes, {sexe_percent['Homme']:.1f}% d'hommes")
print(f"- Catégorie d'âge la plus représentée : {agecat_counts.idxmax()} ({agecat_counts.max()} personnes)")
print(f"- Profession la plus fréquente : {prof_counts.idxmax()} ({prof_counts.max()} personnes)")
print(f"- Statut matrimonial le plus fréquent : {statut_counts.idxmax()} ({statut_counts.max()} personnes)")

print("\nComorbidités les plus fréquentes :")
for _, row in comor_df.head(3).iterrows():
    print(f"  - {row['Comorbidité']} : {row['Effectif']} ({row['Pourcentage']}%)")

print("\nSymptômes les plus fréquents :")
for _, row in symptom_df.head(5).iterrows():
    print(f"  - {row['Symptôme']} : {row['Effectif']} ({row['Pourcentage']}%)")

print("\nComportements préventifs :")
for col in preventive_vars:
    modalite = df_pos[col].mode()[0]  # modalité la plus fréquente
    count = (df_pos[col] == modalite).sum()
    print(f"  - {col} : le plus souvent '{modalite}' ({count} personnes, {count/n_pos*100:.1f}%)")

print("\nQuartiers avec le plus de cas :")
for _, row in top10_pos.head(3).iterrows():
    print(f"  - {row['Quartier_corrige']} : {row['Positifs']} cas (taux {row['Taux_positivite']}%)")

print("\n" + "="*60)
print("ANALYSE DES CAS POSITIFS TERMINÉE")
print("="*60)

Nombre de cas positifs : 1470
Soit 34.0% de l'échantillon total

============================================================
PROFIL DÉMOGRAPHIQUE DES CAS POSITIFS
============================================================

Sexe :
Sexe
Femme    908
Homme    562
Name: count, dtype: int64
Pourcentage :
Sexe
Femme    61.8
Homme    38.2
Name: proportion, dtype: float64

Âge : moyenne = 30.6, médiane = 25.0

Catégorie d'âge :
Categorie_age
Enfant           276
Adolescent       378
Adulte           587
Personne âgée    229
Name: count, dtype: int64

Profession :
Profession
Sans emploi           791
Elève/Etudiant        451
Commerçant             85
Travailleur manuel     65
Agriculteur            46
Fonctionnaire          32
Name: count, dtype: int64

Statut matrimonial :
Statut_matrimonial
Célibataire    702
Marié          627
Veuf           123
Divorcé(e)      18
Name: count, dtype: int64

============================================================
COMORBIDITÉS CHEZ LES POSITIFS
============================================================

Prévalence des comorbidités parmi les positifs :
      Comorbidité  Effectif  Pourcentage
              HTA       134          9.1
Maladie_cardiaque        40          2.7
           Diabte        36          2.4

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\2215274603.py:125: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

============================================================
SYMPTÔMES CHEZ LES POSITIFS
============================================================

Fréquence des symptômes parmi les positifs :
             Symptôme  Effectif  Pourcentage
             Céphalée       275         18.7
Douleurs articulaires       214         14.6
 Douleurs musculaires       198         13.5
               Fièvre       148         10.1
 Douleurs abdominales       138          9.4
           Rhinorrhée        85          5.8
                 Toux        75          5.1
              Nausées        34          2.3
        Conjonctivite        32          2.2
               Sueurs        31          2.1
         Vomissements        31          2.1
          Odynophagie        30          2.0
     Eruption cutanée        27          1.8
             Frissons         9          0.6
              Dyspnée         8          0.5
              Ageusie         6          0.4
              Anosmie         4          0.3
          Rhinorragie         3          0.2

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\2215274603.py:161: FutureWarning:

DataFrame.applymap has been deprecated. Use DataFrame.map instead.

Nombre de symptômes par individu positif : moyenne = 0.9, médiane = 0

============================================================
COMPORTEMENTS PRÉVENTIFS CHEZ LES POSITIFS
============================================================

Distribution des comportements préventifs parmi les positifs :
 Réponse  Effectif                 Comportement  Pourcentage
     Non      1391    Port du masque à domicile         94.6
     Oui        79    Port du masque à domicile          5.4
     Non       861        Port masque exterieur         58.6
     Oui       609        Port masque exterieur         41.4
    Rare       717 Usage du Gel hydroalcoolique         48.8
     Non       671 Usage du Gel hydroalcoolique         45.6
Fréquent        82 Usage du Gel hydroalcoolique          5.6
    Rare       727           Usage savon et eau         49.5
Fréquent       588           Usage savon et eau         40.0
     Non       155           Usage savon et eau         10.5

============================================================
DISTRIBUTION GÉOGRAPHIQUE DES POSITIFS
============================================================

Top 10 des quartiers avec le plus de cas positifs :
Quartier_corrige  Positifs  Total  Taux_positivite
GAMKALLEY GOLLEY       117    165             70.9
      Kirkissoye       115    228             50.4
        Pays bas        95    183             51.9
  ROUTE FILINGUE        87    199             43.7
         Lamorde        79    152             52.0
         Karadje        79    175             45.1
      Boukoki IV        78    140             55.7
          SAGUIA        76    117             65.0
     AEROPORT II        69    198             34.8
   Nord faisceau        68    120             56.7

C:\Users\achao\AppData\Local\Temp\ipykernel_24656\2215274603.py:276: DeprecationWarning:

*scatter_mapbox* is deprecated! Use *scatter_map* instead. Learn more at: https://plotly.com/python/mapbox-to-maplibre/

============================================================
SYNTHÈSE : PROFIL TYPE DU CAS POSITIF
============================================================

- Âge moyen : 30.6 ans
- Sexe : 61.8% de femmes, 38.2% d'hommes
- Catégorie d'âge la plus représentée : Adulte (587 personnes)
- Profession la plus fréquente : Sans emploi (791 personnes)
- Statut matrimonial le plus fréquent : Célibataire (702 personnes)

Comorbidités les plus fréquentes :
  - HTA : 134 (9.1%)
  - Maladie_cardiaque : 40 (2.7%)
  - Diabte : 36 (2.4%)

Symptômes les plus fréquents :
  - Céphalée : 275 (18.7%)
  - Douleurs articulaires : 214 (14.6%)
  - Douleurs musculaires : 198 (13.5%)
  - Fièvre : 148 (10.1%)
  - Douleurs abdominales : 138 (9.4%)

Comportements préventifs :
  - Port du masque à domicile : le plus souvent 'Non' (1391 personnes, 94.6%)
  - Port masque exterieur : le plus souvent 'Non' (861 personnes, 58.6%)
  - Usage du Gel hydroalcoolique : le plus souvent 'Rare' (717 personnes, 48.8%)
  - Usage savon et eau : le plus souvent 'Rare' (727 personnes, 49.5%)

Quartiers avec le plus de cas :
  - GAMKALLEY GOLLEY : 117 cas (taux 70.9%)
  - Kirkissoye : 115 cas (taux 50.4%)
  - Pays bas : 95 cas (taux 51.9%)

============================================================
ANALYSE DES CAS POSITIFS TERMINÉE
============================================================